# Generated by Django 5.2.3 on 2025-07-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chavemestrausuario',
            name='iv',
            field=models.BinaryField(default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chavemestrausuario',
            name='salt',
            field=models.BinaryField(default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'),
            preserve_default=False,
        ),
    ]
