# Generated by Django 5.2.3 on 2025-07-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_chavemestrausuario_iv_chavemestrausuario_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chavemestrausuario',
            name='dado_teste_criptografado',
            field=models.BinaryField(default=0),
            preserve_default=False,
        ),
    ]
