# Generated by Django 5.2.3 on 2025-07-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_chavemestrausuario_dado_teste_criptografado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chavemestrausuario',
            name='dado_teste2_criptografado',
            field=models.BinaryField(default=0),
            preserve_default=False,
        ),
    ]
